apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: APP_ENV
            value: 'Dev'
          - name: KAFKA_BROKER
            value: '10.105.165.100:9094'
          - name: SUCCESS_KAFKA_TOPIC
            value: 'validated-event'
          - name: FAILURE_KAFKA_TOPIC
            value: 'dead-letter-queue'
          - name: MINIO_ENDPOINT
            value: 'http://10.109.34.202:9000'
          - name: MINIO_ACCESS_KEY
            value: 'AgvPf0IgtGyJ3IkpNc0A'
          - name: MINIO_SECRET_KEY
            value: 'jObXuqVj7BnjmuOqJUGk8yocVLHR5CdbYe2NUFWQ'
          - name: MINIO_BUCKET 
            value: 'datasink'
          - name: PYTHON_PATH
            value: 'home/rodrigo/Documents/Projects/trademaster'
