version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    name: postgres

volumes:
  postgres_data:
    driver: local
